name: backend
description: A simple command-line application.
version: 1.0.0
publish_to: 'none'
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  flutterando_analysis: ^0.0.2
  mocktail: ^0.3.0
dependencies: 
  postgresql2: ^1.0.4
  redis: ^3.1.0
  result_dart: ^1.0.5
  shelf: ^1.2.0
  shelf_modular: ^1.0.3
  uno: ^1.0.1+5
